#! /bin/bash


echo
# This stores all the arguments (from `$@`) in an array called `args`
read -r -d ' ' -a args <<< "$@"

# Iterate over args
# NOTE: This is just to print statements according to user input. It is meant to be expandable.
for arg in "${args[@]}"; do

    # Store each character
    read -r -d '\n' -a sarg <<< $(echo "$arg" | grep -o .)

    # Check if the arg starts with a dash and is not followed by another dash
    if [[ ${sarg[0]} == '-' && ${sarg[1]} != '-' ]]; then
        for _arg in "${sarg[@]}"; do
            case $_arg in
                'q') echo '[>] Quickstart'    ;;
                'h') echo '[>] Debug enabled' ;;
            esac
        done
    fi

    # Match big args
    case $arg in
        '--quickstart') echo '[>] Quickstart'    ;;
        '--debug'     ) echo '[>] Debug enabled' ;;
    esac
done
echo

# Her we just run edgequest with all the user arguments
python2.7 -B edgequest.py $@
