#!/bin/bash

# This file:
# * Downloads the latest master from the EdgeQuest repo
# * Overwrites the current EdgeQuest files with the new ones
# * Saves any saved games, and re adds them to the EdgeQuest dir

REPO="https://github.com/surrsurus/edgequest/archive/master.zip"
RNAME="master.zip"
EQLOC="/home/$USER/.edgequest/"
VSP="----------------------------------------------------------"

# If a previous copy exists for some reason, delete it.
if [[ ! -f ${RNAME} ]]; then
    rm ${RNAME}
fi

# If the backup location does not exist, make it.
# FIXME: Backup may not work!
if [[ ! -d ${EQLOC} ]]; then
    mkdir ${EQLOC}
    if [[ ! -d ${EQLOC}/backups ]]; then
        mkdir ${EQLOC}/backups
    fi
fi

# Create a backup of the old branch
tar -cvf ${EQLOC}/backups/backup.tar ..

# Move into the edgequest directory...
cd ..
# ...and delete everything.
echo
echo ${VSP}
echo 'This process will delete any files in your edgequest directory.'
echo 'You should make backups of anything you wish to save now.'
read -p 'Are you sure you want to install? [Y/N] >' -n 1 -r
echo
echo ${VSP}
if [[ $REPLY =~ ^[Yy]$ ]]; then
    cp -f savegame ${EQLOC}/savegame
    rm -rf ./*
else
    echo 'Aborting!'
    exit 1
fi


# This gives us a file called `master.zip`
wget ${REPO}
# Now we unzip it!
unzip ${RNAME}

# Now we are in the directory with `master.zip` and the master folder
# Delete the zip file...
rm ${RNAME}

# Now we move all the actual files out of `edgequest-master` and put them into the correct place.
mv edgequest-master/* .

# And now we are done with that folder, so we remove it
rmdir edgequest-master

# Reload the save file...
cp ${EQLOC}/savegame savegame

# All done!
